TICKERS = [

{ url: 'http://www.finam.ru/analysis/profile0519C/', name: 'Smz-ao' 	      , profile_id: 'profile0519C', percentage: 20 },
{ url: 'http://www.finam.ru/analysis/profile14048/', name: 'iNPONauka'	    , profile_id: 'profile14048', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile13C90/', name: 'iYnet.ru'	      , profile_id: 'profile13C90', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile12342/', name: 'MagadEn ao'	    , profile_id: 'profile12342', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile04F7A/', name: 'MRSKSib'	      , profile_id: 'profile04F7A', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile041E2/', name: 'Rosbank'	      , profile_id: 'profile041E2', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile1400E/', name: 'Electritsink'   , profile_id: 'profile1400E', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile04DCB/', name: 'Arsagera'	      , profile_id: 'profile04DCB', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile2552C/', name: 'Gtl'	          , profile_id: 'profile2552C', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile1421C/', name: 'AbraoDurso'	    , profile_id: 'profile1421C', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile04EEC/', name: 'KuzbasEnergo'	  , profile_id: 'profile04EEC', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile041CA/', name: 'GAZPROM'	      , profile_id: 'profile041CA', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile05256/', name: 'Belon'	        , profile_id: 'profile05256', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile042F1/', name: 'iESKCH'	        , profile_id: 'profile042F1', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile13FC1/', name: 'OrgSint'	      , profile_id: 'profile13FC1', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile04225/', name: 'MosES'	        , profile_id: 'profile04225', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile03ED0/', name: 'Sollers'	      , profile_id: 'profile03ED0', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile089A6/', name: 'Russmore'	      , profile_id: 'profile089A6', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile13F9C/', name: 'ALROSA'	        , profile_id: 'profile13F9C', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile042BE/', name: 'MAGNIT'	        , profile_id: 'profile042BE', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile04379/', name: 'ROSNEFT'	      , profile_id: 'profile04379', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile13FED/', name: 'BURZOLOTO'	    , profile_id: 'profile13FED', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile12341/', name: 'TRANSK'	        , profile_id: 'profile12341', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile253C4/', name: 'MEGAFON'	      , profile_id: 'profile253C4', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile04215/', name: 'MOESK'	        , profile_id: 'profile04215', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile13FDD/', name: 'IZSTAL'	        , profile_id: 'profile13FDD', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile0361F/', name: 'APTEKI36i6'	    , profile_id: 'profile0361F', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile048DE/', name: 'PIK ao'	        , profile_id: 'profile048DE', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile13F5E/', name: 'BASHNEFT pref'	, profile_id: 'profile13F5E', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile00007/', name: 'ROSTELEKOM'	    , profile_id: 'profile00007', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile04DCC/', name: 'KubanEnergoSb'	, profile_id: 'profile04DCC', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile04F2A/', name: 'RUSGIDRO'    	  , profile_id: 'profile04F2A', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile04884/', name: 'DIKSI'	        , profile_id: 'profile04884', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile0521A/', name: 'MECHEL'	        , profile_id: 'profile0521A', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile14021/', name: 'UralSib'	      , profile_id: 'profile14021', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile0021E/', name: 'Lenenergo'	     , profile_id: 'profile0021E', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile0000D/', name: 'SURGUTNEFT pref' , profile_id: 'profile0000D', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile04296/', name: 'NLMK'	           , profile_id: 'profile04296', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile00002/', name: 'GAZPRNEFT'	     , profile_id: 'profile00002', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile00004/', name: 'SURGUTNEFT'	     , profile_id: 'profile00004', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile003F4/', name: 'TRANSNEFT pref'	 , profile_id: 'profile003F4', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile1241B/', name: 'RBK'	            , profile_id: 'profile1241B', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile00017/', name: 'SBERBANK pref'	  , profile_id: 'profile00017', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile13D87/', name: 'Neftekamsk'	    , profile_id: 'profile13D87', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile1404D/', name: 'Gaz'	            , profile_id: 'profile1404D', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile13FFA/', name: 'Tantal'	        , profile_id: 'profile13FFA', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile044BD/', name: 'TGK2'	          , profile_id: 'profile044BD', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile04FBC/', name: 'MRSK sk'	        , profile_id: 'profile04FBC', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile05024/', name: 'INTER RAO'	      , profile_id: 'profile05024', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile047C3/', name: 'Tattel'	        , profile_id: 'profile047C3', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile04F3E/', name: 'Mrsk volg'	      , profile_id: 'profile04F3E', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile0001D/', name: 'Aeroflot'	      , profile_id: 'profile0001D', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile04382/', name: 'TGK5'	          , profile_id: 'profile04382', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile12335/', name: 'Mostotrest'	    , profile_id: 'profile12335', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile2C5D5/', name: 'RN Hold'	        , profile_id: 'profile2C5D5', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile0520A/', name: 'Telegraph'	      , profile_id: 'profile0520A', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile2AEE2/', name: 'GlTorgProduct'	  , profile_id: 'profile2AEE2', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile2C5AA/', name: 'Zivoj Office'	  , profile_id: 'profile2C5AA', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile2C5D6/', name: 'RN Hold pref'	  , profile_id: 'profile2C5D6', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile00033/', name: 'Мегион-ап'	      , profile_id: 'profile00033', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile13AD1/', name: 'TransAero'	      , profile_id: 'profile13AD1', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile2C56A/', name: 'iQIWI'	          , profile_id: 'profile2C56A', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile0449C/', name: 'Akron'	          , profile_id: 'profile0449C', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile0501D/', name: 'FSK ES'	        , profile_id: 'profile0501D', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile04E8B/', name: 'MRSK tsp'	      , profile_id: 'profile04E8B', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile04DF8/', name: 'ChTsZ'	          , profile_id: 'profile04DF8', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile13FC0/', name: 'OrgSintez'	      , profile_id: 'profile13FC0', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile040E2/', name: 'Razgulaj'	      , profile_id: 'profile040E2', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile04F55/', name: 'Mrsk Sz'	        , profile_id: 'profile04F55', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile0020A/', name: 'KubanEnergo'	    , profile_id: 'profile0020A', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile04786/', name: 'Kvadra'      	  , profile_id: 'profile04786', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile13FA5/', name: 'MediaVim'	      , profile_id: 'profile13FA5', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile041A5/', name: 'uaz'	            , profile_id: 'profile041A5', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile13FFE/', name: 'zil'             , profile_id: 'profile13FFE', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile001FF/', name: 'krasnyj okt'     , profile_id: 'profile001FF', percentage: 15 },
{ url: 'http://www.finam.ru/analysis/profile052AE/', name: 'selestra'	      , profile_id: 'profile052AE', percentage: 15 },

]
